### ISSUE TITLE
Add local ip address(es)

### ISSUE THREAD

**Issue by yani** [PurpleBooth/whatismyip#161]
Would be interesting to add something like a `-local` argument.

That way this tool can be used for both external and internal addresses and there would be no need to use something else.

**Comment by PurpleBooth** [comment]
I know you requested this ages ago, but added!

```
$ whatismyip -l
fe80::5a1e:c568:3700:79f
```


```
$ whatismyip -w
dead::beef
```

Will include all of them if you don't provide either 

```
$ whatismyip
fe80::5a1e:c568:3700:79f
dead::beef
```
